Unlock symfony 5 in develop branch
terminal42/contao-leads pull request #120
Opened 2022-03-08 12:47 UTC by rabauss

For Contao 4.13 we need support for symfony 5 in the develop branch!

2022-04-12 08:43 UTC, fritzmg requested changes
This will break any existing listener - you still need to provide the event's name as the second parameter (see also the discussion in  https://github.com/contao/contao/pull/4321). Also you need to drop the Symfony `^3.4` requirement as this will not work in Symfony 3.

2022-04-12 09:46 UTC, rabauss commented on composer.json
>          "php":"^7.1 || ^8.0",
Maybe we should even bump up the php version

2022-04-12 10:03 UTC, rabauss commented on composer.json
>          "php":"^7.1 || ^8.0",
```suggestion
        "php":"^7.4 || ^8.0",
```

2022-05-30 07:38 UTC, merged

2022-05-30 07:38 UTC, aschempp commented
Thank you @rabauss