Update UserNavigationListener.php
terminal42/contao-leads pull request #158
Opened 2024-07-10 10:03 UTC by pressi

Change the Security Class use.
Install Error in Contao Version 5.4.0-RC1

2024-07-10 10:11 UTC, fritzmg requested changes
This makes it incompatible with Contao 4.13.

You should instead change

```php
private readonly Security $security,
```

to

```php
private readonly AuthorizationCheckerInterface $security,
```

(+ the use statement). This will be compatible with all Symfony versions.

2024-07-10 10:22 UTC, pressi commented
ok, good to know, thanks @fritzmg.
i have change this.

2024-07-10 10:32 UTC, fritzmg approved these changes

2024-07-15 18:58 UTC, aschempp requested changes

2024-07-15 18:58 UTC, aschempp commented on src/EventListener/UserNavigationListener.php
> +        private readonly AuthorizationCheckerInterface $security,
Please also change the variable name and its usage in the code.

```suggestion
        private readonly AuthorizationCheckerInterface $authorizationChecker,
```

2024-07-19 10:29 UTC, aschempp approved these changes

2024-07-19 10:29 UTC, merged

2024-07-19 10:29 UTC, aschempp commented
Thank you @pressi è